#!/usr/bin/env bash

trap times EXIT

dir="$1"
cmd="$(realpath "$2")"

(
export PROMPT_STYLE_HOSTNAME=''
export PROMPT_STYLE_BRANCH=''
export PROMPT_STYLE_WD=''
export PROMPT_STYLE_RESET=''

cd "$dir"
for _ in {1..100}; do
    $cmd >/dev/null
done
)
